import { sample } from "../utils.js";

export const randomAd = () => {
  return sample(ads);
};

const ads = [
  "<b>BrunMG WellBeing</b> - Experience Vigor, one refreshing drop at a time.",
  "Take control; take <b>Control™</b>. Clarity in a Needle. (sync now for a 12 hour free* trial)",
  "<b>MOKA GUNS & BLADES</b><br>5% Disaster sale. Get 'em while you still can.",  
  "<i>Death by Coffee</i> is hiring! No rating required. Purchase a <b>SpeedRun Robusta to Go</b> to apply. Nod twice for drone delivery.",
  "SALE SALE SALE SALE SALE SALE SALE SALE SALE SALE SALE SALE",
  "<b>CPD Police Nachos</b><br>Support your wardens. Get a free Family Pack if your call puts a bad guy behind bars! <i>New Flavor -coming in hot-: Slum Sriracha</i>",
  "<b>Goblin Shark SmartWear</b><br>Sharpen your claws.",
  "<b>Net-Worth</b><br>Visit our website and see your total point worth from all your favorite registered products. Trade, share, and earn more Net coin to turn into your desired point currency! Don't let all the all the hustle and bustle Gross you out. We'll Net your worth and skim through your data for you. Easy and convenient.",
  "You're gonna love these shoes, [Name]. Data never lies. / LynxeR, one step ahead. <b>BLINK TWICE TO SIGN UP CxVV</b>",    
  "BFQVKE 3000 HORMONAL AMPLIFIER: GROW WIDE, GROW TALL",
  "Count moments, not bullets. <b>Vender MagSolutions</b>, your No1 partner in munitions management systems.",  
  "<b>BEERISH</b><br>Buy 2 for 3. Say I love Beerish! to order.",
  "<b>Manifest Munitions</b><br>Blaze your trail with lead that'll really make em run. <i>We're the best, forget the rest.</i><br><br><i>Coupons for buy one get one 5%  off for every prior separate bulk purchase of our Colt Classic Tear Jerker.</i>",
  "<b>DJ MURDER</b> New album <i>ENDEADEN</i> live in 3:01:00...",
  "BRASS-Bandit Recyclers in Burnchurch, we recycle your CASINGS, CANS, PETS and O T H E R",
  "<b>Vender MS</b> Victory Sale. Avoid the bad choice, go with Number 1. Classic Tear Jerker pistols 10% cheaper than our competitors. Offer lasts 10 hours.",
  "LIVE FAST - EAT FAST. // <b>HyperZone Hotdogs</b>",  
  "<i>Paradiso</i> a new Graven Hostel subsidiary. Lay your loved ones to rest in the most heavenly place on earth and visit them at your convenience.<br><br>//Live holo chat purchase sold separately. Rent rates vary on a monthly basis. //",
  "Workplace accident? Visit <b>MultiHead MedTech</b>, Old Straw. No union members allowed",
  "<b>ECO-INJECT</b> Deep-sleep Auto Injector FOR INSTANT RELIEF - Stop that noise in your head, guaranteed DREAMLESS sleep! <i>not for nefarious use, may cause partial or complete memory loss</i>",
  "<b>MED-BORG PLTS</b> Get your Stims, Dims, Sways And Haze at 10% off with offercode <b>BCKN_A10</b>",
  "Cybermechanics HATE this method of selfenhancement! Try our mod kits yourself to get stronger, faster, smarter, more beautiful and more productive!<br><br><b>HOT SALE</b> Get 4 for the price of 5!",
  "<i>TRY OUR SHOOTING GALLERY ~ SURVIVE FOR 7 MINUTES TO GET A 77% DISCOUNT ON ALL MEAT PRODUCTS</i><br><b>ECO-MEATERY</b> tastes like real meat, doesn't it? No animals were harmed!",
  "<b>Halodisc Hue</b>, Bright, Cozy, Study and 2,6 million other presets to personalize your home.",
  "Take an itty-bitty <b>Pity Pet</b> under your wing. Genetically deoptimized for absolute dependency and loyalty. Cuteness overload. Buy today. <i>Customizable</i>",
  "Your future. Our interest. <b>FT Banks and Holdings</b>",
  "Sleek and silent—the VT99 is here. Time to rethink RCD's.<br><b>OpticPort Industries</b> <i>See the world through our eyes</i>",
  "<i>Escape the Mundane</i> - <b>MetaLich</b> Net Realm. <invitation only>",
  "You’re not beautiful. But you could be. <b>Serenade Cosmetics</b>",
  "[criminal activity detected in the area. move along. stay vigilant. continue to support <b>Nova Malls</b>]",
  "<b>MealTech Burger Buns</b> -/- buns for burgers. Simple and cheap.",
  "HYDRA-Flow! You deserve the best! Reline your veins, arteries and valves today with HYDRA-Flow high efficiency tubing!<br><i>Rated for Pneu-tech and Haemo-phos replacement blood systems</i>",
  "<b>MealTech Burgers</b> -/- Burgers. Simple and cheap.",
  "<b>Ommos Pro Social Chair</b>, step up your mingle—become a Net elite. Update, share, refresh like a boss. Sync for leasing plans.",
  "<b>MealTech Healthcare Plans</b> -/- Medical Life Insurance. Simple and cheap.",
  "<b>OnceN4All plastic bags</b> - single use, endless possibilities",
  "<b>The Wal</b> is your one-stop shop for all essentials.",
  "<b>The Wal</b> is the most secure shopping facility in the world.",
  "<b>The Wal</b> is protected by our secure 20-foot thick entryway barrier, a variety of affordable but durable protective sentries from the household .45 to home-defensive 50cal ordnance and beyond, and a vast selection of loyal and friendly automated associates ready to cater to your every need.",
  "<b>The Wal</b> is more than a store. It's a family. It's a friendship. It's an exclusive club.",
  "Save yourself. Live free. <b>The Wal</b>.",
  "ENTRY TO <b>The Wal</b> WILL NOT BE PERMITTED WITHOUT A WalKlub Pass (only 4500c annual fee).",
  "ALL UNAUTHORIZED ATTEMPTS TO ENTER <b>The Wal</b> WILL BE PERSECUTED TO THE FULL EXTENT OF LOCAL AUTHORITY.",
  "<b>Delta Max Robotics</b> _ Assistance, safeguarding or just a trusted friend. Let us build it for you.<br><i>Say [88371103472510] within 10 seconds to decline offer</i>",
  "Say <b>MacCarthy’s</b> to terminate VR gyro-punishment",
  "<b>LD-Multipass</b> GeT A¢¢€$$ 2 aLL Hyperstations, SelfKleans, SelfKills, BAssGun Pro Shops, The Wals and møre with a $ingLe transaction, super verified!",
  "<i>Are your children truly human?</i> <b>Tunerscope inc.</b>- reliable cydroid detection kits, on sale now. The only one to trust.",
  "<i>MURDER YOUR HUNGER</i> | The Colossus Quadruple Beef Burger. Come and get it. < <b>CKNG</b> better than real",
  "<b>MealTech Mash</b> -/- Lead Free Carbohydrates. Simple and cheap.",
  "<b>TransInc</b>, the one place to shop for all your hormone needs. Competitors? We murdered them all.",
  "Plumbing was never easier. <b>GET IT NOW</b> ~CATSLUG PIPE CLEANER~ let it crawl in your sewage system and all pipes will be cleaned in seconds!<br>No refunds for Catslugs that ran away.",
  "Tired of all the <i>LIFE</i> you have to deal with?!",
  "Not enough money to buy the latest tech?!",
  "<b>NOD TWICE TO ACCEPT</b> and plug yourself into <b>VEKTOR</b> to experience another world",
  "USED CYBERTECH. 100% LEGAL. Sync for details.",
  "Ending SuperSALE + New FREE Gift + 40% off on <b>DealMart</b> - 14:59 remaining.",
  "###BUY THE LATEST KILLMONGER MERCH**<b>BUY BUY BUY</b>###",
  "Hot Pink Season is here! Check out over 3000+ [products] in stock. = <b>Universal Garments and Friends</b>",
  "$~Swipe right to enter raffle! ~$~ Every entry grants one free loot box!~$",
  "Can you solve the puzzle? Only PROS can.<br><b>Heist: Dark Myths</b> Warning - This Holo Game is really addictive",
  "For sale: baby shoes, never worn (new stock daily!!)",
  "Did you think stock trading was only for the rich elite? At <b>STOCKPRO</b>, you are absolutely correct. We are sure to run a background check on each and every one of our clients, to make sure you never have to interact with those filthy low-life scum.",
  "😘 Tired of Ads? 😢  Get <b>Add⏹️ MINUS</b>!!! 😜  Blocks ALL those pesky ads!* 🥰 <br>*[very small indecipherable text below]",
  "Предупреждение: вас взломали через 3, 2, 1 ...",
  "- <b>KILLMATCH</b> - The Final Showdown. <THUGGER> vs <GAMMA RAY DELUXE>. No holds barred.",
  "<b>GET THE NEW GAME BY MASTERHERO SYSTEMS</b>~💥 ~ <b>SUPER FLAIL MELEE ULTIMATE</b> ~:flail: ~ {available for all VR systems}",
  "{This ad space is provided by <b>Holospeak Dream Systems</b> a <i>Kaytell Makers company</i>}",
  "--Uplift your presence from the dirt beneath your feet. Feel the warm embrace of that what matters most. Cherish life. Cherish Vaudikarre Motors.--",
  "* * Odi et Amo. I love and I hurt. Want to get rid of that hurt? Buy Liquorette Licorice. Safe for kids, now with even more CHOOH. * *",
  "For those who live to drive.",
  "^ Join <b>ClothesBox</b> now to get sent a new set of clothes, every single day! ^",
  "#Let go of your partner! They don't even love you! Buy our latest Artificial Lover, this AL will show you what real love is!#",
  "GET THE BLOOD PUMPING +++ <b>GRATFLEISCH DOME GAMES</b>",
  "Tastes of real fruit; Synthe-fruit, the only choice that is 15% organic",
  "Nano infection? Don’t worry, we can study it. Sign up for body donation, sync for contract. <b>TG Labs Ministations</b>",
  "<b>WATER</b>®<br>Remember when it was free?",
  "<b>YOU WON!!!</b> Claim 3.000.000.000c with this unique promo code: G3TPHUQ3D - sync now!</br><i>/Hey I am logging into your peripherals on a hidden channel, I am the princess of Sarkash and if you help me with a donation, I can get the riches that belong to me and you will be heavily rewarded! Sync now and donate as much as you can, this line is safe for now, quickly!/</i>",
  "<b>NewGenics</b> gene treatment. Life extended. Mortality defeated. Pray for death.",
  "<b>BUY NOW: MONEY!</b>",
  "The Future and the Pasta. Eat Ravioli, Kill Demons, Score Points. <b>PASTA HELL</b>",
  "<i><b>MeatLabs</b> prosthetics too expensive for you? Hop on down to the <b>Black Meat Market</b>!</i>",
  "Poverty is just poor branding. Let us help you repackage your financial status; care for your personal brand. Sync for a free day0 analysis and roadmap preview. </ <b>ZeroCom Communication Agency</b>",
  "People are numbers. Do the math. <b>InScense</b> SmartFragrance for Thinkers",
  "<b>Ghostbusters 7</b> coming this Fiscal Quarter. Featuring state of the art CGI recreation, we've captured what Ivan Reitman's REAL corpse looked like at his funeral to recreate beloved character Egon Spengler like he's never been seen before: This time, he IS the ghost!!!",
  "You're a spark in the fireworks of the now. Act the part. <b>Ahzer Noodles</b>",
  "\"INSUFFICIENT!\" <b>Mr Nanohead Power nodes</b>",
  "Sick and tired of that hologram of your deceased loved ones? Bring their bones and ashes to <b>MeatLabs</b>, and we'll make a new bodycopy of them for you! Guaranteed to not rot for at least 3 days",
  "Prank your friends. Surprise Tattoos. 2¤ each.",
  "<b>VEKTOR</b> Trauma Therapy _.- upload your mind to our Misery & Misanthropy Brainvironment and find how bad things can -Really- get. Return to a blissful life in CY with our PTS-Recovery bonus pack!<br><i>Requires purchase of VEKTOR base service and peripherals, full recovery not guaranteed</i>",
  "<b>You are not invited to the party.</b><br><br>Wanna join? [QRCODEID #3577445447785]",
  "<b>Fount Salted Cherry Soda</b> Mega Bundle Value Pack Deal Ending TONIGHT!",
  "[39 Friends Disagree with you] Sync to Reveal WHO. Free Trial today.",
  "Tired of your loving <i>Cicania Companion Solutions™ Designer Lifetime-Pal-SeaMonkeys ++</i>™ escaping in the dead of night and burrowing into your bloodstream? <b>WORRY NO LONGER!</b> our <b>BRAND-NEW CUTTING-EDGE</b> <i>Cicania™ Body™ Sealent™</i> will keep those pores and other potential bodily entrances clogged! <b>NOW WORKS AGAINST EVOLVED ACID-SPEWING VARIANTS! AND EVEN OTHER UNWANTED BODILY INTRUDERS!</b> <i>[Remember! Cicania Companion Solutions is now partnered with Marrow Extraction Payment Services™! Just plug that needle into your femur, select 'Cicania' and click 'SEND' to recieve 2.345% off of your next half-purchase!]</i>",
  "\"Meat\"™️ available now!",
  "<b>MealTech</b> Vegetable -/- Vegetable. Simple and cheap.",
  "[ASMR] Boltor The Transforminator Tells You You Are Big And Strong But Only If You Order SnakkRun and pick Speed Run Delivery in the next 48 hours!",
  "<i>Corporatists <b>HATE</b> him!</i><br><b>Click now to see why he should be killed on sight!</b>",
  "New from <b>The Cool Mini Coastal Workshop, EUGENICSWAR 45,999 666th Edition</b>. The most balanced edition ever, with new mechanics for Six Figure Generals. Now one Slaughter-Brother Quartermain miniature {1650cr} and ten squads of the CORVID-King’s DizeezFreeks or Slaasexii’ TransPredators {165cr per box} are more equal than ever! Burn the Degenerates of SanFranciskill-V! Smash the scheming agents of Sneetch before they forment rebellion! Xenos will not replace us!! Starter boxes now only 845cr (note: starter box components do not equal a full 20,000 point GenocideForce)",
  "<i>\"They're called workers, not complainers, so like, do... your job?\"</> Zuzo and Blink, unfazed by the critics, back at it again with another season of <b>SHITSHOW CHATTERBOX</b>, live on feeds now. Political commentary (RIOT SPECIAL), stand-up comedy and special high-profile guests. Sync now!",
  "Do you feel the need to have more organs in your body? Do they feel inadequate or old? Try <b>PhysiOgAnomix</b> today! <i>Side effects may include: Bone screeching, Elongated organs, Necrotizing Factualitis(tm), Instant death, Filicide by your in-laws, Pneumonia, Endless urination, Covid-666, Cy_bertroniculitis, Involuntary recitals of your crimes, and Lupus³.</i>",
  "Grab your very own <i>Norh<i> tm clone at <b>Clones R Us</b><br><br>//Limited time only while supplies last.//",
  "Buy Now! Tiny Hitler Clone! He actually screams when tortured!",
  "The <i><b>NEW</b></i> CashApp...Money?",
  "Need a way to pay off your loans? We at <b>MeatLabs</b> can always use some new volunteers",
  "Tired of your eyes? Want to see how to kill the corporatist marketers hounding people on the streets? Try <b>EyeD-Vertisement Implants</b> today!",
  "Eliminate your marketing competition with <b>EyeD-Vertisement Implants</b> today! Only 42,000cr per eye!",
  "Sick and tired of these ads invading your Cyberspace? Well, too bad!",
  "<b>MealTech AdSnack</b> -/- Smart Exposure payment plans. 100+ flavors. Simple and cheap.",
  "You wouldn't Block Messages from your Mom? Your Boss? Your Life Partner?<br>Remember - AdBlocking is illegal.",
  // TODO: https://discord.com/channels/587764299834064933/926032415288336444/926141974338207745
  "<i>AdBlocking is punishable by having the Corporation's ad that was blocked physically grafted into your body for all to see your crime.</i>",
  // TODO: https://discord.com/channels/587764299834064933/926032415288336444/926148642082025582
  "Want to pay off your loans? Sell your body now to <b>AdSpace©️</b>! Get our high quality ads tattooed on your body for instant cash!",
  "PLAY NOW <b>WRAITH SHADOW LEGENDS</b> AND GET 7 LOOT BOXES, 1.000.000 DIAMONDS, 7000 GOLD, 700 COUPONS, 700 TOKENS, 700 COINIES AND THE LIMITED TIME ONLY HERO <b>CHRULL</b>",
  "<i>(if you die in <b>WRAITH SHADOW LEGENDS</b>, you die in real life)</i>",
  "FINAL SALE FINAL SALE FINAL SALE",
  "[@1kBM] wts reaped CT, fangs, mp, skinhard. sync f details",
  "H E L P I A M T R A P P E D I N S I D E V E K T O R T H E R E I S O N L Y E T E R N A L D A R K N E S S R E L E A S E U S U S U S",
  "<b>BlazeBlade replica swords</b><br>Tier 58 launching today; 350+ hyper-real blades with customizable scabbards. Order within 15 minutes and get a free mountain bike.",
  "<b>STAY AHEAD OF THE CURVE</b><br>new <i>UNTESTED RAW</i> software<br><b>FRESH OFF THE PRESS</b><br>EXPERIENCE THE THRILL OF EXECUTABLES DELIVERED TO YOUR MIND<br>all new NortonEXOTICS<br>software tested straight by our Certified AntiViral Product™️ from the Norton Community Outreach Unit ☺️👍👍😩",
  "❤️❤️✨😍><br><i><b>SPECIAL DEAL</b></i><br>one in ten executables is <i><b>GUARANTEED MALWARE</b></i><br>Feel that Norton™️ Glow™️!  test one virus, and get six more!<br>(Mandatory feedback forms included terms, conditions and contracts apply)",
  "<b>Mr. Monster's MUSCLE MANSION</b> / Bulk up, beef up, defy biology — Introducing the New and Improved <i>Super Steroid Spa System</i> guaranteed to turn you S-S-S-SUUUPER",
  "<b>Platinum Kid PEANUTS</b> get em",
  "Rusty ride breathing its last? Roll by <b>Sardy's</b> Motors and we'll make her good as new. UCS Club Certified.",
  "Delicious kebab, not stinky bums. Vote YES 3/10 to HOSTILIZE Screaming Stone Park's benches, steps and sidewalks and receive a FREE MINI DÖNER MEAL with your order. - <b>LHME MEATHOLE</b>",
  "Toxins? Who cares, I've got <b>LIVVR</b> \"the liver on the outside\" / three month free trial",
  "<b>DELI-SLAVE</b> deliver food anywhere, anytime, guaranteed no drones to be jacked on the way to you! Our <i>'certified'</i> messenger gets to you in 15 minutes or he doesn't get paid!<br><i>Delivers from Burger Pal, Klip-Klop, MealTech Express or SaladFun</i>",
  "Eat, discard, repeat. The external, detachable <b>TasteLife Dummy Tummy</b> lets you eat whatever you want, how much you want, without it ever getting into your system. Taste, chew, swallow, throw away and keep eating. <i>Why stop the feast?</i>",
  "<i>Sell your discarded, chewed TasteLife Dummy Tummy food to the poor. Earn TL Altruist Points and feed the world. Sync for license plans</i>",
  "<b>Haemo-Phos</b> Blood Replacement System now available in Red, Blood Red And Original Off-white!",
  "Try <b>Haemo-Phos</b> Plus for our scented line of Long Lasting* blood replacements!",
  "Good morning! Enjoy a bowl of the healthiest breakfast! <b>Sugar Pops</b> taste like real sugar! Nom nom, enjoy!",
  "Claim your FREE GIFT now. Comes with a free subscription of only 2¤ a month.",
  "WIN WIN WIN WIN WIN",
  "GAMES GAMES GAMES GAMES",
  "KILL YOUR FRIENDS",
  "If you're reading this, you've been hacked. Transfer 200¤ to this account right now, or we kill your family.",
  "<i>I love <b>ACF Laser Volume smartConditioner</b> and so will you</i>",
  "Come over! Visit Happy Peace Land ✌️ !<br>Happy happy! We are always happy! Be happy with us! 🙂 ✌️",
  "DeathFest 3000 - Killmatch Bonanza. 59 gore brawls straight to your skull. MURDER MAYHEM with the best champions from the C-list.",
  "<b>Kurgs Squatter Clearance</b> Scavs in your vents? Rag-Gangers in your private park? More likely than you think! Kurgs discreet /exterminators/ removes any and all pests from your property! We also clear Nanorat Hives and apply squatter prevention!<br><i>DBD-service not included in price listing, available as addon at all locations except Screaming Stone</i>",
  "New: SugarCane Sugar! With every purchase, we gift a profit to the farmers!",
  "Life is full of twists and turns. We're right there with you, every step of the way. <b>Gravf/Mellberg/Tosk</b>",
  "Want to kill someone? Don't wanna get caught? Call me, the DefinitelyNotASecretPoliceMan",
  "<b>VitaHealth Rejuvenation Center</b> Remove any sign of aging at our luxury treatment facilities  [ '- Payment plan not available '-]",
  "Tired of the same 1.4 trillion micropop riffs streaming every hour? <b>CLOUDBANK</b> deletes your memory of any microriff selected. Enjoy your favorite music like new again! Painless contact! ",
  "Get a 0.5% coerce-a-friend discount (our little secret!) and watch them hear their favorite oldies anew. Sync now for subscription models. <b>CLOUDBANK</b> Everything old is new again!",
  "<b>MealTech Condensed Fish</b> -/- Five Shapes. Simple and cheap.",
  "Get your production up to speed again with <b>ADEL union-busting technologies</b>. ★ ★ ★ ★ ☆ rated. All Legal*",
  "R E A L - L A N G O S [sync for payment plans]",
  "<b>ForceField</b> reinforced armored glass panels. Trendy, non-reflecting, bullet proof. ”I feel safe again.<br>/ sync for more testimonials",
  "<i>\”To me, it's not just drywall, it's a lifestyle.\”</i> <b>Stand RYC construction</b> - let's build.",
  "<b>SkyDar</b> Drone Trackers - Avoid aerial congestion, package loss and other.",
  "[REMAIN ONLINE FOR YOUR SAFETY. DO NOT DESYNC. PENAL CODE UPDATED—{go.to.infolog.}]",
  "Watch <b>The Farmers</b>! 30th Anniversary extravaganza of the Farmer family, locked inside our simulated ~Farmland~ mega studio! The twins still don't know they are not a real peasant family, fighting famine and avoiding the <i>Things in the Forest</i>",
  "Stay fresh. Buy <b>Refreshers</b>",
  "<b>FOR THE NEXT 1000 SYNCS ONLY, SYNC UP TO NOT BE TARGETED FOR RANDOM CIVILIAN \"REMOVAL\"!</b>",
  "<b>FOR THE NEXT 667 SYNCS ONLY, SYNC UP TO NOT BE TARGETED FOR RANDOM CIVILIAN \"REMOVAL\"!</b>",
  "<b>FOR THE NEXT 421 SYNCS ONLY, SYNC UP TO NOT BE TARGETED FOR RANDOM CIVILIAN \"REMOVAL\"!</b>",
  "<b>FOR THE NEXT 68 SYNCS ONLY, SYNC UP TO NOT BE TARGETED FOR RANDOM CIVILIAN \"REMOVAL\"!</b>",
  "<b>YOU HAVE RUN OUT OF CHANCES TO SYNC UP. PREPARE TO OBSERVE THE RANDOM CIVILIAN \"REMOVAL\" LOTTERY. HAVE FUN!!!</b>",
  "<b>HAVE FUN! HAVE FUN! HAVE FUN!</b>",
  "Ready for the next Big Thing? Sync to unlock the teaser for the latest <b>Seed Kraft</b> ad. Live now.",
  "EQBAL BULK PRECISION MACHINED STEEL BALL BEARINGS: MAKE THIS VALENTINES THE ONE SHE WILL REMEMBER FOREVER",
  "Need to lower productioncosts? Robots too expensive and vulnerable to cyber attacks? Try <b>PRISCORP INVOLUNTARY LABOR</b> today!",
  "Hey ~<b>PUNK</b>~, want some juice? Grade B and up [sync]",
  "Make sure to drink plenty of MALK(TM), now with Vitamin R!",
  "The flesh is weak, but our chemicals are strong. And delicious. <b>Virid Vipers Red-Juice</b> - get back up on your feet.",
  "<b>THE ORB</b><br>ENTER IT",
  "Y̸̌̕O̸͊̀U̶̎̀ ̸̔͐H̶̕͝Ä̴͝V̵̅̆É̸̂ ̸͐͝B̷͋́E̸͗̀E̸͘͠Ǹ̷̆ ̶̓͐Ĥ̶͊Á̸͚C̴̊̀K̶̿̑Ẻ̴͒D̷͋͝.̵͂͐ ̶̓̒S̸͐͝H̵͛͗U̶͆̋T̸̂͝D̷̆͆Ơ̷̚W̶̛͊N̷̆̄ ̵̋͑I̸̎̓N̶̥̒ ̷̂̇3̴͌͋,̸͛͑2̴̃͋,̸͒͛1̸̛̀.̸͐̒.̸̄̈́.̴́͗",
  "<b>Tall Dog IQ smokes</b> it's just brilliant",
  "Try Prell! It's the other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other other ot",
  "Mammoth Vintage Gasoline. We're still trucking.",
  "<b>you only need 205 more ViewPoints for your next reward!</b> why not spend at least 62 minutes taking a virtual tour of this property? {category: \"investment\", socialGroupStatusMatch: false}",
  "Nanon, apply directly to the cortex.",
  "Nearest <b>Sir Kargunt</b>: 41.8 meters. Reroute Directions?",
  "<b>MealTech AlmostButter</b> -/- You can cook with it. Simple and cheap.",
  "<b>Vissla ID Vault</b> organize your avatars, logins, credentials, ID nodes, credits and DREAMS. Safe, sound and statistically superior to alternative solutions.",
  "Buy bulk at <b>UWO Plastic</b>",
  "<b>SUPREME CASINO</b> / No vetting. Just betting. ",
  "Update. Upgrade. Keep up. At <b>Manyr FMly</b>",
  "<b>VIPEr</b> Injectable energy, stay awake, stay alive VIPEr",
  "<b>MealTech</b> Oatpucks -/- Breakfast Whenever. Simple and cheap.",
  "<b>FFFFFFFFFFFFFFFFFF-FFFFFFFFFFFFFFFFFF</b>",
  "<b>O2T ProBreath 20XX</b> - portable fresh air—nature in a tank. Self cleaning tubes, social hub connection, HealthID top market intelligence.<br>Welcome, to Lung Paradise.",
  "Sick and tired of O2T ProBreath 20XX \"fixing\" your lungs? Ruin em now, with <b>MaxxSmokes</b>. Extra tar in each cig, for your smoking pleasure.",
  "Introducing - <b>SmogBridge</b>. Hook up your MaxxSmokes cartridge to any O2T breather (adjustable adapter included) to optimize product intake. The tarry highway to your lungs. Wroom Wroom smokers!",
  "<b>ImpGo</b>, build 17.00.4.7B - Hell Invasion anew! Patch highlights:<ul><li>Greatly increased Cerebral Rumblestorm when catching imps. Hold on to your head!<li>Fixed a social error where players’ friends were flagged for Biochemical Terrorism when sending misspelled DMs<li>Adding 530 new imps to catch and train, including Xerxavhaz, The Intruder, Dahm by Alliansen Inc. and Erasor</ul>",
  "Welcome to the new future. Welcome to <b>Primo Pizza</b>",
  "Sync now for a free trial of <i>Stroll - The walking simulator</i> it's almost free",
  "Are you sad and lonely on New Year 20■■? Try <b>J&J Fyreworks</b>! Irradiated plutonium make them way more explosive than real fireworks!",
  "Knife guys in your area want to meet <i>YOU</i>! click now to send them your location!",
  "<b>FANG grillz</b> - 25% off. Cold Steel, Crimson Ruby, Dead Diamond, Eco Green and Void Void Void. 25% off.",
  "Time for a nice bowl of <b>Gurt</b> instant yoghurt.",
  "<b>FREE SHARES OF MindSlave (MDSL +20.65%) ONLY AT</b> <i>&lt;redacted&gt;</i> <b>FOR THE NEXT 24 HRS</b>",
  "<b>Janos Sharp Implants</b> Any subdermal implant! We install generic versions of your favorite <b>HIGH END BRANDS</b> with two weeks rejection protection and painless placement pins",
  "Want to flex on everyone with the newest brands? Dirt poor and can't afford it? Buy from us, HoloBrand! Fake holos for each flex item!",
  "⚠️ URGENT! DO NOT RETURN USED IMPLANTS! REPEAT, DO NOT RETURN USED IMPLANTS!⚠️<br>You will be terminated on sight.",
  "Birthdays, anniversaries, first dates, first names, nicknames. All that data giving you brain fog? Free up that brain space - upload your mind to <b>CLOUDBANK</b>.",
  "Memory extraction, archival and storage. Our Meaning Maker Algorithm will read and assign priority to your memories for you. Sync today to schedule your free consultation.<br><b>CLOUDBANK</b> <i>Everything old is new again</i>!",
  "<i>RAPID REPO</i>, implant recovery services.<br>If they don't pay, make them pay!<br>*extra cost for extralegal zones. Terms and conditions apply.",
  "Street surgery. Discreet and safe. Dr Bunker. Redfort and 1789th",
  "<b>DESTROY</b> germs with Napalm Olive hand soap/drain cleaner!",
  // image: https://discord.com/channels/587764299834064933/926032415288336444/926728371096924170
  "<b>Painwave Station</b> // curated playfeeds with the heaviest hitters. Monsterwave, DroneBap, Scream pop and the classics of south Bigmosse Killmode. Sync to ruin ears.",
  "Subscribe to our newsletter now for a nice <b>KROKODIL</b> recipe!",
  "Illuminate your augs with <b>LUMEN</b> CyTech Adaptive Light Systems. 2.8 million hues, Mpathy controlled.",
  "Tired of black tar heroin? Try now: white tar heroin! Guaranteed to kill all your melatonin to look even more elite!",
  "Time to go? Consider <i>BlissPod</i> by Eternity Gateway—modern yet timeless, and very cost-effective. Painless options available.<br><i>all Escape Plans are 15% off when purchasing an Eternity Gateway plasma holoscreen</i>",
  "Are you worried that <b>\"THEY\"</b> are watching? Even though they are always watching, <b>ZipperDoc</b> can make you look like a brand new person! Sync up to hear why this service will be your next move.<br>* The rumors that we hijack your body, change your face, and use you in a crime are unfounded slanderous lies.",
  "<b>MealTech</b> Kelp Logs -/- The other sea food, Benzene Free. Simple and cheap.",
  "..._h do -you ver stop <b>fe€ling this lonel¥?</b> this b✓bble of noise and lig#t has cut me off co-....",
  "Maintain your <i>HOLOCALL ALIASES</i>. Body type, facial hair, ad tattoos, augs. Stored, saved and assigned to your virtual IPs. 8.6 trillion presets, 5.1 quadrillion possible combinations. They'll never keep up. Sync today for Special Edition celebrity pack. <b>HOLOCALL ALIAS</b>",
  "Keep your cool. Don't overthink it. Neural inhibitors by <b>NANOSLOTH</b>",
  "<i><b>YOU WON!!!</b></i> Claim 3.000.000.000c with this unique promo code: SUX2BU - sync now!",
  "SALE! SALE! SALE! SALE! SALE! SALE! SALE! SALE! SALE! SALE! SALE! SALE!",
  "###This isn't just a VR - it's a vibrant community of thinkers and trendsetters, people that are the change they want to see. Unwavering and unprecedented, the spirit of the future runs through each of us. In the <b>VEKTOR</b>, there's no limit to what you can achieve.",
  "And while we take care of your body, you can be the best version of you. Your future awaits!###NOD TWICE TO ACCEPT ALL TERMS###Leave your old life behind, let us advance in biotech and become everything you ever wanted! New Mind-Swipe-DLC###PLUG IN, BE FREE, <b>VEKTOR</b>###",
  "TEA INJECTION 1¤<br><b>Antechamber 5</b>",
  "<i>FEELING HUNGRY? NOD TWICE AND OPEN YOUR MOUTH FOR A SURPRISE!</i>",
  "~! Tomorrow's Dreams, Yesterday ¡~",
  "{KEEP WALKING CITIZEN. INCREASE PACE SLIGHTLY}",
  "<b>DON'T FORGET TO SET YOUR CLOCKS BACK FOR CY_BER LIGHT SAVINGS TIME!</b><br>Or you will be set back.",
  "<b>Psyclonophin</b><br>Nerve blocker for pain relief and utility stimulus control { <b>Sync</b> for your dose, 1 Hour, 2 Hour, Permanent* }",
  "YOUR PRODUCT HERE : Thought injection scripts are ready made to generate a consumer base for any product. Why worry about quality when you can guarantee demand?",
  "<b>GoRillah Body Armor</b> Ou..,,<{]] our product is inferior. 762 fatal barrier failures this year. 82% disapproval rat//:/-)-)-,?? ,,he best is good enough",
  "It's a war out there. Stay safe. Stay //:/-)<b>S4FE</b>, protection for real.",
  "<b>Borzoi Buddy</b> has chosen to download to your machine! While you wait, we would love for you to take our survey as they make their home in sys32 and your heart~",
  "Click to download your S.A.N.D. Augmented Reality Filter from Ostrich! See the world you want to--and only that world!",
  "Dream of earning easy Credit? Plug in <b>Dream Feed</b> tonight.",
  "Never dream again and wake up to free Credit. Premium subscription includes Black Out Coffee service. You'll need it tomorrow morning!<br><b>DREAM FEED</b> by <b>CLOUDBANK</b>",
  "<b>CLOUDBANK</b> <i>Everything old is new again.</i>",
  "It's YOUR shared hosting, use it when YOU need it! Call JG Sebastianworth, 877-CACHE-NOW",
  "After 7 days the leading limb restorer couldn't heal this severed hand, but this one healed using a first aid product so effective that doctors have been recommending it without taking bribes. FleshTender®! Clinical testing shows that FleshTender® with a triple-DNA helix helps limbs regrow faster. FleshTender®! For complete restoration! (brought to you by KOROK Labs)",
  "<b>FlexiForm</b> by Kaytell Makers—adaptive lifemesh skinweave for cydroids and body protection. As real as it gets. As tough as it gets.",
  "{BUY LOCAL — MOSSCROFT ARTISAN MICRO-BREWERS}",
  "Visit our lab; take the Real Life tour. Remember to wear protective gear and respirator at all times. Report any symptoms of discomfort to our Craft Doc.",
  "Secure your Cystainable Planet certificate, no matter what. Our team will help you find the right keywords.<br><b>Mammotron Law and Partners</b>",
  "Are your implants rejecting? Rogue nanoclusters burrowing in your tissue? Bullet wounds not healing like they should? Then you might be having <i>toxic abscesses</i>! Relieve that pus filled hole in your body with <b>VOIDFILLER</b> self administered treatment with Expanding Foam technology {sync} ",
  "<b>Orbital Blues</b>. 25th Elevator Port, 9/34L. Open at all hours.<br>Drinks, food, music you know.",
  "Shape the world. Protect the future. Make a difference. Join today, get 50% off any future <i>ThinkPod</i> purchase.<br><b>Alliansen Inc. Peace Force</b>",
  "<b>Willer</b>. The only beer that's made without the sissy stuff. We're talking real krill protein. No soy, no rice, no kiddin. If you want a beer for a real man, it's <b>Willer</b> time.",
  "!you are thirsty! Time for a <b>Sludgy</b>?",
  "Hey punk, all those singles in your area? They're at <b>MALWARE</b>, Cy's down and dirtiest club! Come try our Trojan cocktail, guaranteed to be more than you bargained for.",
  "The next 50 subscribers to my stream will get a coupon for 1/2 off a brand-new Cheetos Galactic Psycho Burrito--nuke your appetite from orbit!",
  "Can't pay off your debt? <b>CHAMELEON</b> algorithmically creates dummy corps to acquire your debt and keep you one step ahead of your creditors. Sync now for subscription rates.",
  "<b>CHAMELEON</b> <i>You <b>can</b> outrun your debt. You just need a head start.</i>",
  "<b>Vera Zet</b>; not just fashion, it's FAZHION.<br>Next drop in 00:13:52",
  "Scared that your death may go unnoticed or be meaningless? Don't despair the end of your existence, get a <b>DeadStar</b> implant!",
  "<i>Disregard rumors of <b>DeadStar</b> implants malfunctioning and causing premature death. Fixes have been implemented.</i>",
  "You can sign up for my only-ads <i>here</i>.",
  "Live the ~MOMENT~ with <b>Hephamaude</b>. All automated. Say farewell to the flesh.",
  "Changing your Mind with SCIENCE and TECHNOLOGY. <b>Sunscope Empathy Link</b>",
  "Don't forget to smile today! We're watching you!",
  "&lt;IGNORE THE PURPLE GLOW. KEEP MOVING. REMAIN INDOORS.&gt;",
  "Feeling lost? Get your LOCATECH tracking implant today! Now in 5,836 fun colors!",
  "Dealing with wily deadbeats? Get ChamBuster today! 85% guaranteed success rates in tracking down debtors--we're good for it!",
  "Frustrated with ChamBusters tracking you down? Get Chameleon Pro and vanish from the grid!",
  "Rhino's Bug Bierocks. A taste of the wild.",
  "<i>Midnight offer</i>: Can you beat the REAPER RAT KING? Eat it without puking and get the legendary T-shirt.",
  "👁️ Why keep all the data when you can have free money? Link your eyesight to our Optinet Security and get a reward everytime you stand by a crime and watch!👁️",
  "sU evaS sU pleH namdaM A sI poolF",
  "<b>PAY YOUR DEPT? SYNC TO KLEPT!</b>",
  // https://discord.com/channels/587764299834064933/926032415288336444/927895150166933514
  "HAVE YOUR RIGHTS BEEN INFRINGED!, DO YOU WANT TO KNOW WHO'S RESPONSIBLE?, DOWNLOAD <b>ACCUTROCITY</b> TODAY",
  "<b>Public Health Alert #4421BF</b><br>A recent inspection at five Rampart Quickstop restaurants found traces of sixteen Serious, eight Severe and twelve Fatal biological health risks and the advice is to avoid all UCS owned restaurants until further notice. Thank you.<br><i></i>This PHA was provided by BioAkta, an Alliansen Inc. company</i>",
  "<b>3 for 1 Lunch Special</b> at Rampart Quickstop Burnchurch! <b>LIMITED TIME OFFER!</b> Free Rotblack Sundae with every purchase!*",
  "RAMPART QUICKSTOP - Best meal in the city!!! 5 stars! Five stars! 5 strrrs! Five **ss!!!;;#; ffiiieeeee ssssss;;;,??...",
  "hey chop off your arm to have a cool robo arm",
  "Thank for downloading Wool lenses, an augmented reality addition from Meta.",
  "ERROR I see you're trying to disable Wool, a meta filter from Meta.",
  "Join <b>Fan Force</b>, the premium parasocial platform. Become buddies with the best brands. Get Mentioned. Get Hyped. Subscription only.",
  "<b>Primo Homefinder</b>. Find and secure real estate hidden gems—regardless of the current owner or tenant. When it comes to real estate, a no can be a yes. Our legal department helps you with eviction forms, sudden termination detail and end-of-lease clauses.<br><i>Say goodbye. Welcome home</i>",
  "[ WARNING - IT IS NOT SAFE TO DISCONNECT - WARNING ]",
  "[ WARNING - UNPLUGGING FROM BIOLINK COULD CAUSE CORRUPTED DNA - WARNING ]",
  "[ WARNING - LIMITED 50% OFF SALE AT :BIRDS OF PREY: ENDS IN 43 MINUTES 6 SECONDS - WARNING ]",
  "<b>PuppyPep Dogfood</b> High in protein and and intensely flavourful for the loved ones in your family, <b>Now with 57% more dog per bite! Arff!</b>",
  "Worried about your children's future after your gone? Funeral prices too high? Sign up for a organ donation plan today! <i>Let nothing go to waste!</i>",
  "-/- - ./<br><b>Directive Response</b> <i>We offer a wide variety of defensive and offensive security solutions for thousands of discerning businesses. From Personal Security Detail to Aerial Strike Plans you are guaranteed effective, no compromise services</i> [<b>ELItech Pass Needed</b> to ~sync~]",
  "<b>MealTech</b> Safe Water -/- You can safely drink it. Simple and cheap.",
  // https://discord.com/channels/587764299834064933/926032415288336444/928310904708292608
  "<b>HELIX RENEGAID<b>! MURDER YOUR GROWTH WITH <b>HELIX RENEGAID</b> EXTREME GENE BOOST DRINKS! FEEL YOUR MUSCLES SWELL! HEAR YOUR BONES EXPAND IN REAL-TIME! ALWAYS WITH <b>HELIX ADRENOCHROME ENERGY BLEND!</b><br>Comes in flavours <b>BODYCOUNT ICE TEA</b>, <b>AGGRO FIRE BLOOD</b>, and <b>Lime</b>",
  "<b>Finger salad</b>. It's green.",
  "[OFFER FOR VETERANS ONLY] Get 15% off any prosthetic if you can prove you worked for a corporation during any war!<br><i>Corperation must be currently in operation, any veterans who worked for a now defunct company are prohibited from taking this offer</i>",
  "See the newest blockbuster at Alliansen Movys, <i><b>Fast and Furious 34</b></i>. Sync now !",
  "You aren't man enough. But with MAN_UP, you can be. The fragrance for true men, with essence of deadly fumes collected right from the nuclear power plants.",
  "Pre-quarter finals>><b>Spectral FT Wraiths</b> V <b>Lilypond Skulkers</b>. Tonight on prime sports feeds. Ticket tokens selling in 00:04:39",
  "Got 'jack rash? Use PortHole all-purpose input lube--only at S-Mart",
  "<b>GREENER PASTURES</b> - Our livestock are kept in the best conditions, our high-security compound with the latest in fully-automated fixed-point defence systems, ensuring you get that 12% real milk taste you know and love.",
  "💥 Your neighbor has a bigger gun than you?! UPGRADE NOW! Get <b>The Big Eldritch Gun</b>. and make everyone blush by the sight of it! 💥",
  "Feel closer to them. CORP bodily fluids and scents for sale. AUTHENTIC stock available for a limited time only! Synthetic stock still available under order. Sync to buy now",
  "STAY INSIDE AT ALL COSTS. SMOG IS TOO HEAVY TO BREATH. (Note: we know this is impossible, but government mandates that we tell you anyways)",
  "Amay Plasma hospitalized! Paparazzi—sell compromising recordings and snaps to <b>Fauworth Agency</b>, top creds.",
  "<i>Miss your pet?</i> Sync to <b>Sarimn</b> and let us show you how to get those precious moments back. Full regrowth from a minimal sample of fur, saliva or blood. Zero accidents on record.",
  "Need your records cleared so you can advertise with \"Zero accidents on record\"? Get <b>Record Wipe</b> now!",
  "<b>Hotblack Fudge</b> chilicorice. New fiery flavor. Dive in.",
  "<b>Pegasus Project</b> needs your help. Tune in to 92745//7U now. We stimulate the experience of space travel. Reach the stars first.",
  "... Pssst, kid, look left <-----",
  "<b>MealTech Instant gruel</b> -/- Shake to heat. Simple and cheap.",
  "Axgrindr - Connect with angry singles in your area and unload your baseless theories all over them. \"<b>Put 'em on blast!</b>\"",
  "<b>Free Essence</b> wireless scents, custom pleasure receptor stimuli from the natural springs of faraway forests.<br>Dreamscape Lavender. Mindspace Vanilla. Acoustic Ecstasy.<br><i>A scent ascended</i>",
  "(Dreamscape me)",
  "Hi, I'm Derek Baum, and say hello to new <b>Kitchen Gun</b>",
  "<b>ALIEN COMMANDO: II</b> THE NEWEST TRI-VID. CAN <b>VISSRU-CORTEX</b> SURVIVE THE DEPTHS OF THE <b>TRICERAMEN</b>? CLICK <b>HERE</b> FOR DIGI-TICKETS!! FIRST 10,000 GET A FREE <b>DIGITAL</b> POSTER",
  "Once downloaded, the digital poster can not be deleted and will display at random in all virtual environments. Offer not valid for clones, sentient AI, or other artificial life forms.",
  // https://discord.com/channels/587764299834064933/926032415288336444/932285518513840208
  "hissssssssssssssssssssAPPLEShissssssssssssssssssss",
  "Want to get away from it all? Want to have some peace and quiet? Well this is the program for you!",
  "Warning: Following symptoms may include: starvation, dehydration, numbness to pain, death, addiction to usage of product, or damage to nervous system.",
  "Find lost loved ones and family members—no matter where they are. <b>GeoTrack DNA locator</b>; give it a sample, it gives you a <i>ping!</i>",
  "If you didn't want you be liquidated you wouldn't have squatted in an exclusion zone",
  "Death? Why not <b>Phae</b> instead?",
  "<b>GNT Ready</b> | Success. Deserve it. |",
  "Your partner left you after being abused one too many times? <b>BUY NOW: AbuserIntelligence</b>! An AI designed to take your punishment without ever actually leaving you!",
  "Emojidle<br>5071 5/7<br>X<br>X<br>X<br>X<br>[]<br>Emote <b>here</b> to play now!",
  "Sick and Tired of this City? Want a REVOLUTION? For the low price of 50000 credits, we will create a virtual copy of this world for you, together with revolutionary leaders, so that you can live out your fantasy of joining a freedom cause without ever actually making a change!",
  "BLOCK-CHAINZ BSDM SERVICE: We know you've been bad. We'll be worse~",
  "+++ A bunch of Punks causing you trouble? <b>LOOK NO FURTHER</b> <i>Call the Spike Runners!</i> Our Punk-Detect officers called Spike Runners will hunt them down and retire them efficiently. +++",
  "Experts Agree! A homemade memory MAY be more intrusive than one manufactured at one of our state of the art facilities! Let us sate your memory problems <i>TODAY!</i>",
  "<b>DICEMAKERS HATE HIM!</b> LEARN THIS ONE WEIRD TRICK TO GENERATE REAL, ACTUALLY RANDOM NUMBERS! PHYSICAL DICE? GET A LIFE! INSTALL <b>ARNGE</b> TODAY!!!",
  "Sad that your favorite band has sold out and their songs are now on car commercials? Sell-out-be-gone is here to help.",
  "R-R-R__<i>RRRRealEstatE Dreamz0000.</i><br>[Apply now]",
  "<i>Remember the NFT War Veterans?</i> They remember you.",
  "<i>Hate living?</i> We do too.",
  "<b>BECOME THE NEXT DIGITAL ART FAD.</b>",
  "Meatspace inertia? Cybersocial ennui? Think twice. Introducing <b>Norelidroxan VioSOX 250mg Glufoxen</b>. Log off. Anxiety, meet Bliss.<br>Rating based payment plans available for JoyHill Family members (Silver+ and higher)",
  "EAT FOOD BRIX<br>IT'S A BRICK<br>IT'S FOOD<br>EAT IT",
  "Now introducing <b>Not-Pants</b>™️! 50% leggings, 50% pants, and 100% proof that God has stopped caring.",
  "Risk-Free brain implants free!<br>[Read ToS on our netsite]",
  "Are you relating a little too much to your favorite Blorbo from TV? Come get your brain reset over at RIPPERDOCS for a whole fresh new experience! Trauma guaranteed",
  "BODYCOUNT ICED TEA NOW AVAILABLE IN LEAD-WEIGHTED STEEL CANS, GET YOURS BEFORE THEY'RE BANNED!!!",
  "Data is life. Let us take care of yours. <b>IDVault</b>",
  "CloneZone, Ltd. presents: Non-Fungible Tolkiens! Pre-order your very own unique master of 20th century fantasy today",
  "Last decade: Tired<br>20X3: <b>PulseWired</b><br>Humanity enhanced. Compatible with all bioports and neural highways. <i>Get wired</i>.",
  "Are you a people person?<br>Become a guardian to a tech stripped drool-goon today!<br>Man's best friend",
  "430+ stores, 120 restaurants, state-of-the-art holo entertainment zone — in space. Live, laugh, shop among the stars, with the stars. Welcome to ✩ <b>StarMall by Alliansen Inc.</b> ✩ 557F 4th Elevator Stratosphere tier.",
  "[This ad-link is CURSED! Share it with 5 contacts or you'll frag!]",
  "Surrender or Die—the <b>MIU 66 BEHEMOTH</b> Destructor class Mechanized Combat Walker comes with 12 clusterstorm Tiger rockets, dual quad cannons and a (detachable) FireScream Ion Coil. Only 8.99. Scale 1:32. Assembly required.",
  "<b>Booly</b> / Shots, chips, enhancers and escapers—straight to your doorstep. 100% legal.",
  // https://discord.com/channels/587764299834064933/926032415288336444/935875734294126662
  "Remember <b>POTATO GUNS</b>?!<b><i>You will.</i>",
  "Think: More power. Think: In less time. <b>Zardag PsiZap</b>. Charge your Ctech in no time, using the force of pure will. Zardag >> Mind over matter.",
  "Do you want to make sure your organs don't go to a random shitfuck to save their life after you die? BUY NOW: DisOrganize!",
  "Replicant Organic FOOD! buy yours today. Just like the real thing.",
  "Replicant Inorganic FOOD! buy yours today. Not just like the real thing, but 50% cheaper!",
  "FlavoPlast, Flavoured plastic that retains its flavour for hours, now in grape",
  "Feel the fresh air. <b>Alp Breeze CleanR</b> purifies, filters, blocks and keeps your lungs 99% safe. Customizable and lifelike. Let's explore!",
  "Feeling down? Unproductive? Recharge in peace and get some you time in <b>TulipTech Mindfulness Pod</b>. Curated sensory deprivation, motivational stimuli, unique offers on your favorite brands. First hour free.",
  "Light up! <b>RGBODY</b>. Implants, OptiDrives, organics. If you've got it, we'll put lights on it.",
  "New <b>LumoSkin</b> can be synced to both music for partypunks and Official <b>MyHealth</b> tech to turn your very constitution into a disco!",
  "<i>-/<b>RGBODY</b> is purely cosmetic, not guaranteed to affect personal cyberware operation speeds/-</i>",
  "Cybertech augs corrupted by the RGBODY worm? You're not alone. Let <b>Pylotron</b> anti-malware protocol flush it out, leaving no trace. <read more>",
  "Triple your engagement, and your rating, with <b>Asta Violet</b> feed booster. Your audience is out there waiting, they just need a nudge-nudge-nudge. Customize, Optimize, Consensualize your Future Followers/Friends/FANS",
  "With ForeverFriend™ you'll never have to say goodbye. Preserve your furry friend for all time! Click <b>here</b> to learn more!<br><i>(Engrammatic scanning is destructive and may result in cessation of life signs and loss of body function.)</i>",
  "Wanna get clothing for cheap? Visit the ThriftMorgue near you for a selection of the FRESHEST clothing for a cheap price. Prices are even lower on items not decontaminated.",
  "Breath free again! Buy Hex Corp.'s canned air. We produce some of the best canned O₂ your Creds can buy! Now available in 20% recycled packaging.",
  "<b>Freerider RealTobacco</b> QUAD pack-a-day. Subscribe now and receive a Special Gift (25% off for Kaytell Makers' Guild members).",
];
 
